name: 'Publish AWS Lambda'
decription: 'Publish layer package file to AWS S3.'
author: 'reinhed'
inputs:
  bucket-name:
    description: 'The S3 bucket name.'
    required: true
  zip-file-name:
    description: 'The name of the zip file.'
    required: true
  layer-name:
    description: 'The name of the layer.'
    required: true
  layer-description:
    description: 'Layer short description.'
    required: true
  function-name:
    description: 'Name of the function to update.'
    required: true
outputs:
  layer-version-arn:
    description: 'Layer version amazon resource number.'
runs:
  using: 'node16'
  main: 'main.mjs'