name: 'Deploy to AWS S3'
decription: 'Deploy a static website via AWS S3.'
inputs:
  bucket:
    description: 'The S3 bucket name.'
    required: true
  bucket-region:
    description: 'The S3 bucket region.' 
    required: false
    default: 'us-west-1'
  dist-folder:
    description: 'The folder containing deployalble files.'
    required: true
outputs:
  website-url:
    description: 'The URL of the deployed website.'
runs:
  using: 'node16'
  main: 'main.js'