name: Full Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: develop
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BUILD_KEY: ${{ github.sha }}

    steps: 
      - name: Get Config Repo
        uses: actions/checkout@v4
        with:
          path: build/loyalty-ops-layer-config

      - name: List Root Directory
        run: |
          cd build/loyalty-ops-layer-config/nodejs
          pwd
          ls -R

      - name: Package Modules Layer
        run: |
          cd build/loyalty-ops-layer-config/nodejs
          ls -lrt
          find . -maxdepth 1 -mindepth 1 -type d | while IFS= read -r line; do echo `cp default.js ${line}`; done
          cd ../
          ls -lrt
          zip -vr layer_delta_${{ env.BUILD_KEY }}_${{ vars.ENV_NAME }}.zip nodejs/ -x "*.DS_Store"
          ls -lrt

      - name: Clean Up Build Staging
        run: |
          cd build/loyalty-ops-layer-config/nodejs
          find . -maxdepth 1 -mindepth 1 -type d | while IFS= read -r line; do echo `rm -f ${line}/default.js`; done

      - name: Upload Layer Assets
        uses: actions/upload-artifact@v3
        with:
          name: build_assets
          path: build/loyalty-ops-layer-config/layer_delta_${{ env.BUILD_KEY }}_${{ vars.ENV_NAME }}.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: develop
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BUILD_KEY: ${{ github.sha }}

    steps:
      - name: Get Config Repo
        uses: actions/checkout@v4
        with:
          path: build/loyalty-ops-layer-config
      - name: Get Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build_assets
          path: build/loyalty-ops-layer-config
      - name: Output Contents
        run: ls -R
      - name: Output Contents
        run: ls ./build/loyalty-ops-layer-config/.github/actions/deploy-layer-js -a -R
      - name: Deploy Layer
        id: deploy
        uses: ./build/loyalty-ops-layer-config/.github/actions/deploy-layer-js
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket: ${{ vars.DEPLOYMENT_BUCKET }}
          bucket-region: ${{ env.AWS_REGION }}
          dist-folder: ./loyalty-ops-layer-config
